// SPDX-License-Identifier: GPL-2.0+
#define CLOCK_GPIO_VREG	0x1e0
#define CLOCK_GPIO_DREG 0x0d8
#define CLOCK_GPIO_BIT	16
#define DATA_GPIO_VREG	0x1e0
#define DATA_GPIO_DREG	0x0d8
#define DATA_GPIO_BIT	18
#define TRANS_GPIO_VREG	0x080
#define TRANS_GPIO_DREG	0x0d0
#define TRANS_GPIO_BIT	10

#define SYS_SIG		SYS_SIG_ROMULUS
