// SPDX-License-Identifier: GPL-2.0+
#define CLOCK_GPIO_VREG	0x000
#define CLOCK_GPIO_DREG 0x0c0
#define CLOCK_GPIO_BIT	4
#define DATA_GPIO_VREG	0x000
#define DATA_GPIO_DREG	0x0c0
#define DATA_GPIO_BIT	5
#define TRANS_GPIO_VREG	0x020
#define TRANS_GPIO_DREG	0x0c4
#define TRANS_GPIO_BIT	30

#define SYS_SIG		SYS_SIG_PALMETTO

#define CONTINUOUS_CLOCKING
#define EXTRA_DUMMY_READ
